### ISSUE TITLE
TypeError: Cannot read property 'string' of undefined

### ISSUE THREAD

**Issue by Talha-T** [s-coimbra21/react-hextech#1]
Reproduction steps:

1-) `create-react-app empty-dir`
2-) `npm install react-hextech`
3-) in app.js to following:
```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import { Button } from "react-hextech";

class App extends Component {
  render() {
    return (
      <div className="App">
        <Button/>
      </div>
    );
  }
}

export default App;
```
4-) `npm start` , you should see the error: `TypeError: Cannot read property 'string' of undefined`
  ![758adb5f-2d57-4ba6-a383-df2731520e06](https://user-images.githubusercontent.com/25489715/41201219-4062c9b2-6cbc-11e8-8872-e4e72a6fef58.png)
`

**Comment by Talha-T** [comment]
no fix yet?

**Comment by s-coimbra21** [comment]
working on it

**Comment by s-coimbra21** [comment]
I think the issue is due to the React version I'm using for this lib. I'll update to React 16 when I can.

**Comment by s-coimbra21** [comment]
@Talha-T try version 2.0.1 from NPM

**Comment by Talha-T** [comment]
I will try in the morning - thanks

**Comment by Talha-T** [comment]
```
import React from "react";
const Hex = require("react-hextech");

export default () => (<Hex.Button>Test!</Hex.Button>);
```

result: 
![60f56591-c2b9-46cb-a3eb-4f40227554c6](https://user-images.githubusercontent.com/25489715/41510432-2919e946-726d-11e8-8ee2-1e004ddb4801.png)

**Comment by Talha-T** [comment]
I can't use {} imports because intellisense doesn't suggest anything.

**Comment by s-coimbra21** [comment]
try importing the styles

import 'react-hextech/lib/styles.css'

**Comment by Talha-T** [comment]
fixed
